
# last updated 2024-12-18 1800

image_refs_htmls = {
    
    # Countries
    r"icons8-switzerland-96.png": """<a target="_blank" href="https://icons8.com/icon/15526/switzerland">Switzerland</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-sweden-96.png": """<a target="_blank" href="https://icons8.com/icon/15527/sweden">Sweden</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-slovenia-96.png": """<a target="_blank" href="https://icons8.com/icon/17966/slovenia">Slovenia</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-slovakia-96.png": """<a target="_blank" href="https://icons8.com/icon/17965/slovakia">Slovakia</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-norway-96.png": """<a target="_blank" href="https://icons8.com/icon/15544/norway">Norway</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-netherlands-96.png": """<a target="_blank" href="https://icons8.com/icon/15536/netherlands">Netherlands</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-latvia-96.png": """<a target="_blank" href="https://icons8.com/icon/15524/latvia">Latvia</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-great-britain-96.png": """<a target="_blank" href="https://icons8.com/icon/15534/great-britain">Great Britain</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-japan-96.png": """<a target="_blank" href="https://icons8.com/icon/22435/japan">Japan</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-finland-96.png": """<a target="_blank" href="https://icons8.com/icon/15511/finland">Finland</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-france-96.png": """<a target="_blank" href="https://icons8.com/icon/15497/france">France</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-germany-96.png": """<a target="_blank" href="https://icons8.com/icon/15502/germany">Germany</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-czech-republic-96.png": """<a target="_blank" href="https://icons8.com/icon/15513/czech-republic">Czech Republic</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-denmark-96.png": """<a target="_blank" href="https://icons8.com/icon/15520/denmark">Denmark</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-canada-96.png": """<a target="_blank" href="https://icons8.com/icon/15512/canada">Canada</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-austria-96.png": """<a target="_blank" href="https://icons8.com/icon/15506/austria">Austria</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-russian-federation-96.png": """<a target="_blank" href="https://icons8.com/icon/15528/russian-federation">Russian Federation</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-usa-96.png": """<a target="_blank" href="https://icons8.com/icon/15532/usa">USA</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-kazakhstan-96.png": """<a target="_blank" href="https://icons8.com/icon/37274/kazakhstan">Kazakhstan</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",

    # US States
    r"icons8-alabama-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/FXgk2XOgWT7M/alabama-flag">Alabama Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-alaska-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/Aib05gDheyNf/alaska-flag">Alaska Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-california-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/Vos-tGVy-9iR/california-flag">California Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-colorado-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/vnYmQQ4X0JsA/colorado-flag">Colorado Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-florida-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/s1-q7JfG-sh7/florida-flag">Florida Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-georgia-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/NDrD4CYtRBwQ/georgia-flag">Georgia Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-hawaii-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/kbSQX7XfBI5h/hawaii-flag">Hawaii Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-texas-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/XTantlC-UA3q/texas-flag">Texas Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-virginia-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/GAE6WZTPKYO1/virginia-flag">Virginia Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-washington-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/J5GxnkQaXFtb/washington-flag">Washington Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-massachusetts-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/U-ALwM5OpR7S/massachusetts-flag">Massachusetts Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-nevada-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/TKorkvgkXnqa/nevada-flag">Nevada Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-ohio-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/44fY7vWjhjiH/ohio-flag">Ohio Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-oregon-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/X-lScXq7uV90/oregon-flag">Oregon Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-arkansas-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/jQPaxKFfArNp/arkansas-flag">Arkansas Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-wisconsin-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/Y23SDXCP-XCb/wisconsin-flag">Wisconsin Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-kentucky-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/IyhPFm2AXnFh/kentucky-flag">Kentucky Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-indiana-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/AGO0jdY-bkmt/indiana-flag">Indiana Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-minnesota-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/jZHsrwgZA1OV/minnesota-flag">Minnesota Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-pennsylvania-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/VoWoTmq3C4SB/pennsylvania-flag">Pennsylvania Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-idaho-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/zpkl1Hbgzf7W/idaho-flag">Idaho Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-mississippi-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/rw08FzGx83AK/mississippi-flag">Mississippi Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-michigan-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/l39NAYp3jpyq/michigan-flag">Michigan Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-missouri-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/hMYv_tfME4iE/missouri-flag">Missouri Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-oklahoma-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/5I0q-mn8NKdv/oklahoma-flag">Oklahoma Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-montana-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/PiDPd3RIB-aI/montana-flag">Montana Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-delaware-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/fcpZguwMtVSs/delaware-flag">Delaware Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-iowa-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/HtXyBhiNrojW/iowa-flag">Iowa Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-maine-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/drFlVZjrpy3u/maine-flag">Maine Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-connecticut-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/hYXb8jExIHVj/connecticut-flag">Connecticut Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-kansas-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/0u4UrZ-kAH9O/kansas-flag">Kansas Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-illinois-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/c_e0JWgTsNNx/illinois-flag">Illinois Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-lousiana-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/mxUcnMuNAOSp/lousiana-flag">Lousiana Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-maryland-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/9FKO1QSdmhdH/maryland-flag">Maryland Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-nebraska-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/fVBKgBFYEsAS/nebraska-flag">Nebraska Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-new-hampshire-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/ViZFYL8OnHoI/new-hampshire-flag">New Hampshire Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-new-jersey-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/6wBSXgD-30f4/new-jersey-flag">New Jersey Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-new-mexico-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/uKYT_MT6Af1M/new-mexico-flag">New Mexico Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-new-york-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/PHJN-9UdTYcq/new-york-flag">New York Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-north-carolina-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/h4spXYDZr-ez/north-carolina-flag">North Carolina Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-north-dakota-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/HG94AoyH021p/north-dakota-flag">North Dakota Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-rhode-island-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/bEdKRwxEQ3bR/rhode-island-flag">Rhode Island Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-south-carolina-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/lvMLadGC2uIq/south-carolina-flag">South Carolina Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-south-dakota-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/LGWMf_LvV35D/south-dakota-flag">South Dakota Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-utah-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/DoreHlNCT-va/utah-flag">Utah Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-vermont-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/y1Sr8HgfqBOL/vermont-flag">Vermont Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-west-virginia-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/TKwBVwV4ffLU/west-virginia-flag">West Virginia Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>""",
    r"icons8-wyoming-flag-96.png": """<a target="_blank" href="https://icons8.com/icon/kZS0xbjHYerT/wyoming-flag">Wyoming Flag</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>"""
}