

-- Initial inserts to [NHLdb].[dbo].[Teams]


INSERT INTO [NHLdb].[dbo].[Teams] ([FullName], [ShortName], [CommonName], [Abbrev], [NHLAPI_TeamID], [NHLAPI_FranchiseID])
VALUES
('New Jersey Devils', 'Devils', 'Devils', 'NJD', 1, 23),
('New York Islanders', 'Islanders', 'Isles', 'NYI', 2, 22),
('New York Rangers', 'Rangers', 'Rangers', 'NYR', 3, 10),
('Philadelphia Flyers', 'Flyers', 'Flyers', 'PHI', 4, 16),
('Pittsburgh Penguins', 'Penguins', 'Pens', 'PIT', 5, 17),
('Boston Bruins', 'Bruins', 'Bruins', 'BOS', 6, 6),
('Buffalo Sabres', 'Sabres', 'Sabres', 'BUF', 7, 19),
('Montréal Canadiens', 'Canadiens', 'Habs', 'MTL', 8, 1),
('Ottawa Senators', 'Senators', 'Sens', 'OTT', 9, 30),
('Toronto Maple Leafs', 'Maple Leafs', 'Leafs', 'TOR', 10, 5),
('Atlanta Thrashers', 'Thrashers', 'Thrashers', 'ATL', 11, 35),
('Carolina Hurricanes', 'Hurricanes', 'Canes', 'CAR', 12, 26),
('Florida Panthers', 'Panthers', 'Panthers', 'FLA', 13, 33),
('Tampa Bay Lightning', 'Lightning', 'Bolts', 'TBL', 14, 31),
('Washington Capitals', 'Capitals', 'Caps', 'WSH', 15, 24),
('Chicago Blackhawks', 'Blackhawks', 'Hawks', 'CHI', 16, 11),
('Detroit Red Wings', 'Red Wings', 'Wings', 'DET', 17, 12),
('Nashville Predators', 'Predators', 'Preds', 'NSH', 18, 34),
('St. Louis Blues', 'Blues', 'Blues', 'STL', 19, 18),
('Calgary Flames', 'Flames', 'Flames', 'CGY', 20, 21),
('Colorado Avalanche', 'Avalanche', 'Avs', 'COL', 21, 27),
('Edmonton Oilers', 'Oilers', 'Oilers', 'EDM', 22, 25),
('Vancouver Canucks', 'Canucks', 'Canucks', 'VAN', 23, 20),
('Anaheim Ducks', 'Ducks', 'Ducks', 'ANA', 24, 32),
('Dallas Stars', 'Stars', 'Stars', 'DAL', 25, 15),
('Los Angeles Kings', 'Kings', 'Kings', 'LAK', 26, 14),
('Phoenix Coyotes', 'Coyotes', 'Coyotes', 'PHX', 27, 28),
('San Jose Sharks', 'Sharks', 'Sharks', 'SJS', 28, 29),
('Columbus Blue Jackets', 'Blue Jackets', 'Jackets', 'CBJ', 29, 36),
('Minnesota Wild', 'Wild', 'Wild', 'MIN', 30, 37),
('Minnesota North Stars', 'North Stars', 'North Stars', 'MNS', 31, 15),
('Quebec Nordiques', 'Nordiques', 'Nordiques', 'QUE', 32, 27),
('Winnipeg Jets (1979)', 'Jets', 'Jets', 'WIN', 33, 28),
('Hartford Whalers', 'Whalers', 'Whalers', 'HFD', 34, 26),
('Colorado Rockies', 'Rockies', 'Rockies', 'CLR', 35, 23),
('Ottawa Senators (1917)', 'Senators', 'Senators', 'SEN', 36, 3),
('Hamilton Tigers', 'Tigers', 'Tigers', 'HAM', 37, 4),
('Pittsburgh Pirates', 'Pirates', 'Pirates', 'PIR', 38, 9),
('Philadelphia Quakers', 'Quakers', 'Quakers', 'QUA', 39, 9),
('Detroit Cougars', 'Cougars', 'Cougars', 'DCG', 40, 12),
('Montreal Wanderers', 'Wanderers', 'Wanderers', 'MWN', 41, 2),
('Quebec Bulldogs', 'Bulldogs', 'Bulldogs', 'QBD', 42, 4),
('Montreal Maroons', 'Maroons', 'Maroons', 'MMR', 43, 7),
('New York Americans', 'Americans', 'Americans', 'NYA', 44, 8),
('St. Louis Eagles', 'Eagles', 'Eagles', 'SLE', 45, 3),
('Oakland Seals', 'Seals', 'Seals', 'OAK', 46, 13),
('Atlanta Flames', 'Flames', 'Flames', 'AFM', 47, 21),
('Kansas City Scouts', 'Scouts', 'Scouts', 'KCS', 48, 23),
('Cleveland Barons', 'Barons', 'Barons', 'CLE', 49, 13),
('Detroit Falcons', 'Falcons', 'Falcons', 'DFL', 50, 12),
('Brooklyn Americans', 'Americans', 'Americans', 'BRK', 51, 8),
('Winnipeg Jets', 'Jets', 'Jets', 'WPG', 52, 35),
('Arizona Coyotes', 'Coyotes', 'Coyotes', 'ARI', 53, 28),
('Vegas Golden Knights', 'Golden Knights', 'Knights', 'VGK', 54, 38),
('Seattle Kraken', 'Kraken', 'Kraken', 'SEA', 55, 39),
('California Golden Seals', 'Golden Seals', 'Seals', 'CGS', 56, 13),
('Toronto Arenas', 'Arenas', 'Arenas', 'TAN', 57, 5),
('Toronto St. Patricks', 'Patricks', 'Patricks', 'TSP', 58, 5),
('Utah Hockey Club', 'Hockey Club', 'Hockey Club', 'UTA', 59, 40),
('To be determined', 'To be determined', 'To be determined', 'TBD', 70, NULL),
('NHL', 'To be determined', 'NHL', 'NHL', 99, NULL)
